version: "3.4"

services:
  db:
    image: mongo

  app:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:${PORT}"
    env_file:
      - .env

